@extends('layouts.default')
@section('title')
Urugendo - Abo turibo
@stop
@section('content')
<section style="text-align:left">

<div class="container">
	<h4 class="title text-center">Privacy Conditions</h4>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-fbb2faf6-32b5-569e-8265-895e42de4315"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Urugendo.rw is a service provided by NILZ Ltd. The following terms you or user refer to each person visiting </span><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">http://www.urugendo.rw</span><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">. The terms we and our website refer to Urugendo.rw. Protecting your personal data is very important to us. By visiting our website, you provide us with some personal data. This policy explains how we use it. You can visit our website and explore it without providing us with personal data.</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">What information do we collect about you?</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">We only collect personal information from you when you order services on our website, when you complete any customer survey, or through cookies.</span><br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">We collect this information in order to enable orders, such as name, address, phone number, or payment information.</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Cookies and Google Analytics</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Accepting cookies is not necessary to visit our website, but mandatory in order to complete correctly an order.</span><br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">What are cookies? Cookies are small text files placed on your computer while visiting websites. They are necessary to have websites work more efficiently or to provide information to the website&rsquo;s owners. We collect cookies to remember your IP address, so that you can save time when coming back on our website. To get more information about cookies, please visit </span><a href="http://www.allaboutcookies.org" style="text-decoration:none;"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 255); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">www.allaboutcookies.org</span></a><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">.</span></span></p>
&nbsp;

<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span id="docs-internal-guid-fbb2faf6-32b5-569e-8265-895e42de4315"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">As you browse </span><a href="http://www.urugendo.rw" style="text-decoration:none;"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 255); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">www.urugendo.rw</span></a><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> , advertising cookies will be placed on your computer so that we can understand what you are interested in. Our display advertising partners, then enables us to present you with retargeting advertising on other sites based on your previous interaction with &nbsp;</span><a href="http://www.urugendo.rw" style="text-decoration:none;"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 255); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">www.urugendo.rw</span></a><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> . The techniques our partners employ do not collect personal information such as your name, email address, postal address, or telephone number. </span><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">&nbsp;</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">http://www.urugendo.rw</span><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> uses Google Analytics, a web analytics service provided by Google, Inc. (&quot;Google&quot;). Google Analytics uses &quot;cookies&quot; (see above). The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within a EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it: </span><a href="https://tools.google.com/dlpage/gaoptout" style="text-decoration:none;"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 255); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">https://tools.google.com/dlpage/gaoptout</span></a><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">.</span><br class="kix-line-break" />
<br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">How will we use the information we collect from you?</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">We collect and use your personal data on secured servers. We ask third organisms to check and certify our confidentiality principles.</span><br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Information that we collect from you is used to process your order and to manage your account. We may also use your information to email you about other products or services that we think may be of interest to you.</span><br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">In processing your order we may send your information to credit reference and fraud prevention agencies, or to third companies (Travel Agencies and delivering companies).</span><br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">From time to time we may send your information to third parties which we consider may have goods or services which are of interest to you. If you do not wish to be contacted by third parties please email us at &nbsp;</span><a href="mailto:urugendo.rw@gmail.com" style="text-decoration:none;"><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 255); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">urugendo.rw@gmail.com</span></a><span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"> </span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Access to your information</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">At any time, you can request a copy of the information we hold on you. Simply contact us at urugendo.rw@gmail.com. We will ask you a small charge in order to process your request.</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Other Websites</span><br class="kix-line-break" />
<br class="kix-line-break" />
<span style="font-size: 16px; font-family: Cambria; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Our website may have links to other websites. This privacy policy only applies to this website. You should therefore read the privacy policies of the other websites when you are using those sites.</span></span></p>

<div>&nbsp;</div>

</div>
</section>
@stop
